use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006008
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Theron
Stanford
shixilun
Nathan
Glenn
garfieldnate
Royal
Skousen
Nick
nlogan
lib
Algorithm
AM
lattice
Batch
algorithm
DataSet
Item
BigInt
Result
